// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/v1/analytics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/analytics.get').default>>>>
    }
    '/api/v1/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/login.post').default>>>>
    }
    '/api/v1/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/me.get').default>>>>
    }
    '/api/v1/billing/reactivate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/billing/reactivate.post').default>>>>
    }
    '/api/v1/feedback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/feedback.get').default>>>>
    }
    '/api/v1/locations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/locations.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}