// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26.05.2026, 14:16:09
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/domains/ratingo/admin-panel/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/domains/ratingo/admin-panel/src/modules/analytics/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/domains/ratingo/admin-panel/src/modules/feedback/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/domains/ratingo/admin-panel/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/domains/ratingo/admin-panel/plugins/**/*.{js,ts,mjs}","D:/domains/ratingo/admin-panel/src/stores/**/*.{js,ts,mjs}","D:/domains/ratingo/admin-panel/src/composables/**/*.{js,ts,mjs}","D:/domains/ratingo/admin-panel/src/utils/**/*.{js,ts,mjs}","D:/domains/ratingo/admin-panel/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/domains/ratingo/admin-panel/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/domains/ratingo/admin-panel/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/domains/ratingo/admin-panel/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;